import { useEffect, useState, useRef } from "react";
import Navbar from "../components/Navbar";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export default function Report() {
  const [results, setResults] = useState([]);
  const reportRef = useRef();

  useEffect(() => {
    fetchResults();
  }, []);

  const fetchResults = async () => {
    const token = localStorage.getItem("token");

    const res = await fetch("/api/results", {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    const data = await res.json();
    setResults(Array.isArray(data) ? data : []);
  };

  const user = JSON.parse(localStorage.getItem("user"));

  const avg =
    results.length > 0
      ? results.reduce((a, b) => a + (b.score || 0), 0) / results.length
      : 0;

  let risk = "Low";
  if (avg < 40) risk = "High";
  else if (avg < 70) risk = "Moderate";

  const suggestions = [
    "Practice memory exercises daily",
    "Maintain a healthy sleep cycle",
    "Engage in reading and problem solving",
    "Stay socially active",
  ];

  const downloadPDF = async () => {
    const canvas = await html2canvas(reportRef.current);
    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "mm", "a4");

    const imgWidth = 210;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 0, 0, imgWidth, imgHeight);
    pdf.save("CogniScan_Report.pdf");
  };

  return (
    <div>
      <Navbar />

      <div style={styles.page}>
        <h2 style={styles.title}>📄 Cognitive Assessment Report</h2>

        {/* 📄 REPORT */}
        <div ref={reportRef} style={styles.report}>
          
          {/* HEADER */}
          <div style={styles.header}>
            <h1 style={styles.brand}>🧠 CogniScan AI</h1>
            <p style={styles.subtitle}>
              Cognitive & Speech Analysis Report
            </p>
          </div>

          {/* USER DETAILS */}
          <section style={styles.section}>
            <h3 style={styles.sectionTitle}>👤 User Details</h3>
            <div style={styles.grid}>
              <p><strong>Name:</strong> {user?.name}</p>
              <p><strong>Email:</strong> {user?.email}</p>
              <p><strong>Date:</strong> {new Date().toLocaleDateString()}</p>
            </div>
          </section>

          {/* TEST HISTORY */}
          <section style={styles.section}>
            <h3 style={styles.sectionTitle}>📊 Test History</h3>

            {results.length === 0 ? (
              <p style={styles.empty}>No test data available</p>
            ) : (
              <div style={styles.history}>
                {results.map((r, i) => (
                  <div key={i} style={styles.historyItem}>
                    <span>{r.type?.toUpperCase() || "TEST"}</span>
                    <span style={styles.score}>{r.score}/100</span>
                  </div>
                ))}
              </div>
            )}
          </section>

          {/* ANALYSIS */}
          <section style={styles.section}>
            <h3 style={styles.sectionTitle}>📈 Final Analysis</h3>

            <div style={styles.analysisBox}>
              <p><strong>Average Score:</strong> {avg.toFixed(1)}</p>
              <p>
                <strong>Risk Level:</strong>{" "}
                <span style={styles[risk]}>{risk}</span>
              </p>
            </div>
          </section>

          {/* SUGGESTIONS */}
          <section style={styles.section}>
            <h3 style={styles.sectionTitle}>💡 Suggestions</h3>

            <ul style={styles.list}>
              {suggestions.map((s, i) => (
                <li key={i}>{s}</li>
              ))}
            </ul>
          </section>

          {/* FOOTER */}
          <div style={styles.footer}>
            <p>Generated by CogniScan AI</p>
          </div>
        </div>

        {/* BUTTONS */}
        <div style={styles.actions}>
          <button style={styles.primaryBtn} onClick={downloadPDF}>
            ⬇ Download PDF
          </button>

          
        </div>
      </div>
    </div>
  );
}

const styles = {
  page: {
    minHeight: "100vh",
    padding: "40px 20px",
    background: "linear-gradient(135deg, #e3f2fd, #fce4ec)",
    fontFamily: "Inter, sans-serif",
    textAlign: "center",
  },

  title: {
    marginBottom: "25px",
    fontWeight: "600",
    color: "#1a1a1a",
  },

  report: {
    background: "#fff",
    maxWidth: "750px",
    margin: "auto",
    padding: "30px",
    borderRadius: "18px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.1)",
    textAlign: "left",
  },

  header: {
    borderBottom: "1px solid #eee",
    marginBottom: "20px",
    paddingBottom: "10px",
  },

  brand: {
    margin: 0,
    color: "#1976d2",
  },

  subtitle: {
    fontSize: "14px",
    color: "#666",
  },

  section: {
    marginBottom: "20px",
  },

  sectionTitle: {
    marginBottom: "10px",
    color: "#333",
  },

  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
  },

  history: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },

  historyItem: {
    display: "flex",
    justifyContent: "space-between",
    background: "#f9f9f9",
    padding: "10px",
    borderRadius: "8px",
  },

  score: {
    fontWeight: "600",
    color: "#1976d2",
  },

  analysisBox: {
    background: "#f5faff",
    padding: "15px",
    borderRadius: "10px",
  },

  High: { color: "#d32f2f", fontWeight: "600" },
  Moderate: { color: "#f9a825", fontWeight: "600" },
  Low: { color: "#2e7d32", fontWeight: "600" },

  list: {
    paddingLeft: "20px",
  },

  footer: {
    marginTop: "20px",
    fontSize: "12px",
    textAlign: "center",
    color: "#888",
  },

  actions: {
    marginTop: "20px",
    display: "flex",
    justifyContent: "center",
    gap: "15px",
  },

  primaryBtn: {
  padding: "12px 22px",
  borderRadius: "12px",
  border: "none",
  background: "linear-gradient(135deg, #1976d2, #42a5f5)",
  color: "white",
  cursor: "pointer",
  fontWeight: "600",
  boxShadow: "0 6px 15px rgba(25,118,210,0.3)",
  },

  secondaryBtn: {
    padding: "10px 20px",
    borderRadius: "10px",
    border: "1px solid #1976d2",
    background: "white",
    color: "#1976d2",
    cursor: "pointer",
  },

  empty: {
    color: "#888",
  },
};